Repository googleapis/python-phishingprotection, pull requests merged in 2020-06, with the labels that each got.

#17 chore: update templates
  .flake8
  .gitignore
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.7/continuous.cfg
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.7/presubmit.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.8/continuous.cfg
  .kokoro/samples/python3.8/periodic.cfg
  .kokoro/samples/python3.8/presubmit.cfg
  .kokoro/test-samples.sh
  MANIFEST.in
  docs/conf.py
  docs/index.rst
  docs/multiprocessing.rst
  google/cloud/phishingprotection_v1beta1/gapic/phishing_protection_service_client.py
  google/cloud/phishingprotection_v1beta1/gapic/transports/phishing_protection_service_grpc_transport.py
  google/cloud/phishingprotection_v1beta1/proto/phishingprotection_pb2.py
  noxfile.py
  scripts/decrypt-secrets.sh
  scripts/readme-gen/readme_gen.py
  scripts/readme-gen/templates/README.tmpl.rst
  scripts/readme-gen/templates/auth.tmpl.rst
  scripts/readme-gen/templates/auth_api_key.tmpl.rst
  scripts/readme-gen/templates/install_deps.tmpl.rst
  scripts/readme-gen/templates/install_portaudio.tmpl.rst
  synth.metadata
  testing/.gitignore
Labels: cla: yes, context: full

#21 chore: update docs/conf.py
  docs/conf.py
  synth.metadata
  synth.py
Labels: automerge, cla: yes, context: partial

#22 feat: release as beta
  .repo-metadata.json
  README.rst
  setup.py
Labels: automerge, cla: yes
