Repository googleapis/python-phishingprotection, pull requests merged in 2021-04, with the labels that each got.

#59 chore: start tracking obsolete files
  synth.metadata
Labels: api: phishingprotection, cla: yes, context: full

#60 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: phishingprotection, automerge, cla: yes, context: full

#61 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: phishingprotection, cla: yes, context: full, samples

#62 chore: prevent normalization of semver versioning
  setup.py
Labels: api: phishingprotection, cla: yes

#63 chore: update templates
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: phishingprotection, automerge, cla: yes, context: full

#64 chore(revert): revert preventing normalization
  setup.py
Labels: api: phishingprotection, cla: yes
